begin;
create table public.dating_profiles(id uuid primary key references auth.users on delete cascade,name text not null check(length(trim(name)) between 1 and 40),age int not null check(age between 18 and 100),borough text not null check(borough in ('Bronx','Brooklyn','Manhattan','Queens','Staten Island')),bio text not null default '' check(length(bio)<=400));
create table public.dating_likes(sender uuid references public.dating_profiles on delete cascade,recipient uuid references public.dating_profiles on delete cascade,primary key(sender,recipient),check(sender<>recipient));
create table public.dating_blocks(sender uuid references public.dating_profiles on delete cascade,recipient uuid references public.dating_profiles on delete cascade,primary key(sender,recipient),check(sender<>recipient));
create table public.dating_messages(id uuid primary key default gen_random_uuid(),sender uuid not null references public.dating_profiles on delete cascade,recipient uuid not null references public.dating_profiles on delete cascade,body text not null check(length(trim(body)) between 1 and 1000),created_at timestamptz not null default now(),check(sender<>recipient));
create index dating_messages_pair on public.dating_messages(sender,recipient,created_at);
create table public.dating_reports(id uuid primary key default gen_random_uuid(),sender uuid not null references public.dating_profiles on delete cascade,recipient uuid not null references public.dating_profiles on delete cascade,reason text not null check(length(trim(reason)) between 1 and 1000),created_at timestamptz not null default now(),check(sender<>recipient));
create function public.dating_is_blocked(a uuid,b uuid) returns boolean language sql stable security definer set search_path='' as $$ select (a=auth.uid() or b=auth.uid()) and exists(select 1 from public.dating_blocks where (sender=a and recipient=b) or (sender=b and recipient=a)); $$;
create function public.dating_can_chat(a uuid,b uuid) returns boolean language sql stable security definer set search_path='' as $$ select (a=auth.uid() or b=auth.uid()) and a<>b and not public.dating_is_blocked(a,b) and exists(select 1 from public.dating_likes where sender=a and recipient=b) and exists(select 1 from public.dating_likes where sender=b and recipient=a); $$;
create function public.dating_has_profile() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.dating_profiles where id=auth.uid()); $$;
revoke all on function public.dating_is_blocked(uuid,uuid),public.dating_can_chat(uuid,uuid),public.dating_has_profile() from public;
grant execute on function public.dating_is_blocked(uuid,uuid),public.dating_can_chat(uuid,uuid),public.dating_has_profile() to authenticated;
alter table public.dating_profiles enable row level security;
alter table public.dating_likes enable row level security;
alter table public.dating_blocks enable row level security;
alter table public.dating_messages enable row level security;
alter table public.dating_reports enable row level security;
create policy profiles_read on public.dating_profiles for select to authenticated using(id=auth.uid() or(public.dating_has_profile() and not public.dating_is_blocked(auth.uid(),id)));
create policy profiles_insert on public.dating_profiles for insert to authenticated with check(id=auth.uid());
create policy profiles_update on public.dating_profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy likes_read on public.dating_likes for select to authenticated using(sender=auth.uid() or recipient=auth.uid());
create policy likes_insert on public.dating_likes for insert to authenticated with check(sender=auth.uid() and not public.dating_is_blocked(sender,recipient));
create policy likes_delete on public.dating_likes for delete to authenticated using(sender=auth.uid());
create policy blocks_read on public.dating_blocks for select to authenticated using(sender=auth.uid());
create policy blocks_insert on public.dating_blocks for insert to authenticated with check(sender=auth.uid());
create policy blocks_delete on public.dating_blocks for delete to authenticated using(sender=auth.uid());
create policy messages_read on public.dating_messages for select to authenticated using((sender=auth.uid() or recipient=auth.uid()) and public.dating_can_chat(sender,recipient));
create policy messages_insert on public.dating_messages for insert to authenticated with check(sender=auth.uid() and public.dating_can_chat(sender,recipient));
create policy reports_insert on public.dating_reports for insert to authenticated with check(sender=auth.uid());
revoke all on public.dating_profiles,public.dating_likes,public.dating_blocks,public.dating_messages,public.dating_reports from anon,authenticated;
grant select,insert,update on public.dating_profiles to authenticated;
grant select,insert,delete on public.dating_likes,public.dating_blocks to authenticated;
grant select,insert on public.dating_messages to authenticated;
grant insert on public.dating_reports to authenticated;
commit;

