begin;
create table public.profiles(id uuid primary key references auth.users on delete cascade,name text not null check(length(trim(name)) between 1 and 40),age int not null check(age between 18 and 100),borough text not null check(borough in ('Bronx','Brooklyn','Manhattan','Queens','Staten Island')),bio text not null default '' check(length(bio)<=400));
create table public.likes(sender uuid references public.profiles on delete cascade,recipient uuid references public.profiles on delete cascade,primary key(sender,recipient),check(sender<>recipient));
create table public.blocks(sender uuid references public.profiles on delete cascade,recipient uuid references public.profiles on delete cascade,primary key(sender,recipient),check(sender<>recipient));
create table public.messages(id uuid primary key default gen_random_uuid(),sender uuid not null references public.profiles on delete cascade,recipient uuid not null references public.profiles on delete cascade,body text not null check(length(trim(body)) between 1 and 1000),created_at timestamptz not null default now(),check(sender<>recipient));
create index messages_pair on public.messages(sender,recipient,created_at);
create table public.reports(id uuid primary key default gen_random_uuid(),sender uuid not null references public.profiles on delete cascade,recipient uuid not null references public.profiles on delete cascade,reason text not null check(length(trim(reason)) between 1 and 1000),created_at timestamptz not null default now(),check(sender<>recipient));
create function public.is_blocked(a uuid,b uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.blocks where (sender=a and recipient=b) or (sender=b and recipient=a)); $$;
create function public.can_chat(a uuid,b uuid) returns boolean language sql stable security definer set search_path='' as $$ select a<>b and not public.is_blocked(a,b) and exists(select 1 from public.likes where sender=a and recipient=b) and exists(select 1 from public.likes where sender=b and recipient=a); $$;
create function public.has_profile() returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.profiles where id=auth.uid()); $$;
revoke all on function public.is_blocked(uuid,uuid),public.can_chat(uuid,uuid),public.has_profile() from public;
grant execute on function public.is_blocked(uuid,uuid),public.can_chat(uuid,uuid),public.has_profile() to authenticated;
alter table public.profiles enable row level security;
alter table public.likes enable row level security;
alter table public.blocks enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(id=auth.uid() or(public.has_profile() and not public.is_blocked(auth.uid(),id)));
create policy profiles_insert on public.profiles for insert to authenticated with check(id=auth.uid());
create policy profiles_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy likes_read on public.likes for select to authenticated using(sender=auth.uid() or recipient=auth.uid());
create policy likes_insert on public.likes for insert to authenticated with check(sender=auth.uid() and not public.is_blocked(sender,recipient));
create policy likes_delete on public.likes for delete to authenticated using(sender=auth.uid());
create policy blocks_read on public.blocks for select to authenticated using(sender=auth.uid());
create policy blocks_insert on public.blocks for insert to authenticated with check(sender=auth.uid());
create policy blocks_delete on public.blocks for delete to authenticated using(sender=auth.uid());
create policy messages_read on public.messages for select to authenticated using((sender=auth.uid() or recipient=auth.uid()) and public.can_chat(sender,recipient));
create policy messages_insert on public.messages for insert to authenticated with check(sender=auth.uid() and public.can_chat(sender,recipient));
create policy reports_insert on public.reports for insert to authenticated with check(sender=auth.uid());
revoke all on public.profiles,public.likes,public.blocks,public.messages,public.reports from anon,authenticated;
grant select,insert,update on public.profiles to authenticated;
grant select,insert,delete on public.likes,public.blocks to authenticated;
grant select,insert on public.messages to authenticated;
grant insert on public.reports to authenticated;
commit;
