import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext();
const errors=[];
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const origin='http://127.0.0.1:5180';
await page.goto(origin+'/?auth=signin');await page.getByRole('heading',{name:'Welcome back.'}).waitFor();
await page.getByRole('button',{name:'Create account',exact:true}).click();
await page.getByRole('heading',{name:'Find your people.'}).waitFor();
await page.getByRole('button',{name:'Forgot password?'}).click();
await page.getByRole('heading',{name:'Let’s get you back in.'}).waitFor();
await page.getByRole('button',{name:'Sign in',exact:true}).click();
const id='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const base={age:27,borough:'Bronx',bio:'Coffee and live music.',neighborhood:'Riverdale',intention:'Casual dating',gender:'Woman',interested_in:['Everyone'],interests:['Coffee'],photo_paths:[],available_until:null,visible:true};
let own={...base,id,name:'Jamie'},person={...base,id:other,name:'Jules'},likes=[{sender:id,recipient:other},{sender:other,recipient:id}],messages=[];
await context.addInitScript(({id})=>{localStorage.setItem('after-hours-auth',JSON.stringify({access_token:'test-token',refresh_token:'test-refresh',expires_at:Math.floor(Date.now()/1000)+3600,expires_in:3600,token_type:'bearer',user:{id,email:'test@example.com',aud:'authenticated',role:'authenticated',app_metadata:{provider:'email'},user_metadata:{}}}))},{id});
await page.route('https://*.supabase.co/**',async route=>{const req=route.request(),u=new URL(req.url());let data=[];const method=req.method();if(method==='OPTIONS'){await route.fulfill({status:200,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'*'}});return}if(u.pathname.includes('/auth/'))data={id,email:'test@example.com'};else if(u.pathname.endsWith('dating_profiles')){if(method==='GET')data=u.searchParams.get('id')===`eq.${id}`?own:[person];else{const changes=req.postDataJSON();own={...own,...changes};data=own}}else if(u.pathname.endsWith('dating_likes')){if(method==='DELETE')likes=[];data=likes}else if(u.pathname.endsWith('dating_can_chat'))data=likes.length===2;else if(u.pathname.endsWith('dating_blocks'))data=[];else if(u.pathname.endsWith('dating_messages')){if(method==='POST'){const m={...req.postDataJSON(),id:'msg-one',created_at:new Date().toISOString()};messages.push(m);data=m}else data=[...messages].reverse()}else if(u.pathname.endsWith('dating_reports'))data={};await route.fulfill({status:200,contentType:'application/json',headers:{'access-control-allow-origin':'*'},body:JSON.stringify(data)})});
await page.reload();await page.getByRole('heading',{name:'Find your kind of person.'}).waitFor();
await page.getByRole('button',{name:/Matches/}).click();await page.getByRole('heading',{name:/Start with hello/}).waitFor();
await page.getByRole('button',{name:'Say hello ↗',exact:true}).click();
await page.getByRole('textbox',{name:'Message',exact:true}).fill('Hello from a browser test');await page.getByRole('button',{name:'Send ↗'}).click();await page.locator('.bubble').filter({hasText:'Hello from a browser test'}).waitFor();
await page.getByRole('button',{name:'Profile',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Updated Jamie');await page.getByRole('button',{name:'Save profile ↗'}).click();await page.getByText('Your profile is saved.').waitFor();assert.equal(own.name,'Updated Jamie');
await page.getByRole('button',{name:'View Jules\'s profile'}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog').count(),0);
await page.setViewportSize({width:390,height:844});await mkdir('release',{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'release/mobile-preview.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'release/desktop-preview.png',fullPage:true});
assert.deepEqual(errors,[]);console.log('Browser checks passed: authentication screens, mutual-match chat, profile saving, modal keyboard handling, mobile overflow.');
await browser.close();
