import React from 'react';
async function duration(file){
 const url=URL.createObjectURL(file),video=document.createElement('video');
 try{return await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{video.removeAttribute('src');video.load();reject(Error('Could not read this video. Choose a different MP4 or WebM.'))},10000);video.preload='metadata';video.onloadedmetadata=()=>{clearTimeout(timer);resolve(video.duration)};video.onerror=()=>{clearTimeout(timer);reject(Error('This video cannot be played. Choose an MP4 or WebM.'))};video.src=url})}finally{URL.revokeObjectURL(url)}
}
export function VideoEditor({db,profile,ready,busy,act,reload,videoUrl,feedback}){
 async function upload(e){const file=e.target.files?.[0];e.target.value='';if(!file)return;await act(async()=>{if(!['video/mp4','video/webm'].includes(file.type)||file.size>26214400)throw Error('Choose an MP4 or WebM under 25 MB.');const seconds=await duration(file);if(!Number.isFinite(seconds)||seconds<=0||seconds>30)throw Error('Choose a video no longer than 30 seconds.');const path=`${profile.id}/${crypto.randomUUID()}.${file.type==='video/mp4'?'mp4':'webm'}`;const result=await db.storage.from('dating-videos').upload(path,file,{contentType:file.type});if(result.error)throw result.error;const saved=await db.from('dating_profiles').update({video_path:path}).eq('id',profile.id);if(saved.error){await db.storage.from('dating-videos').remove([path]);throw saved.error}if(profile.video_path)await db.storage.from('dating-videos').remove([profile.video_path]);await reload();feedback('Your video introduction is saved.')})}
 async function remove(){await act(async()=>{const result=await db.from('dating_profiles').update({video_path:null}).eq('id',profile.id);if(result.error)throw result.error;const cleaned=await db.storage.from('dating-videos').remove([profile.video_path]);await reload();feedback(cleaned.error?'Video hidden; storage cleanup failed.':'Video removed.',cleaned.error?'error':'success')})}
 return <section className="video-editor"><h3>A little more you</h3><p>Add one video introduction. Up to 30 seconds, 25 MB. MP4 or WebM.</p>{videoUrl&&<video className="profile-video" src={videoUrl} controls playsInline preload="metadata"/>}{profile.video_path&&<button className="text-button" disabled={busy} onClick={remove}>Remove video</button>}<label className="photo-upload">＋ {profile.video_path?'Replace':'Add'} a video<input type="file" accept="video/mp4,video/webm" onChange={upload} disabled={busy||!ready||!profile.id}/></label>{!ready&&<p className="fine">Video and contact features need the media database update.</p>}<p className="fine">Share only media you own or have permission to use. Visible to eligible signed-in members.</p></section>;
}
