import React,{useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
const url=import.meta.env.VITE_SUPABASE_URL,key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const db=url&&key?createClient(url,key):null;
const boroughs=['Bronx','Brooklyn','Manhattan','Queens','Staten Island'];
const blank={name:'',age:25,borough:'Bronx',bio:''};
export default function LiveApp(){
const [session,S]=useState(null),[tab,T]=useState('Discover'),[profile,P]=useState(blank),[people,PP]=useState([]),[likes,L]=useState([]),[email,E]=useState(''),[password,W]=useState(''),[signup,U]=useState(false),[adult,A]=useState(false),[notice,N]=useState(''),[busy,B]=useState(false),[selected,C]=useState(null),[messages,M]=useState([]),[body,D]=useState(''),[borough,F]=useState('All NYC'),[recovery,R]=useState(false),[report,Q]=useState(null),[reason,V]=useState('');
const uid=session?.user.id;
function check(r){if(r.error)throw r.error;return r.data}
async function run(fn){B(true);N('');try{await fn()}catch(e){N(e.message)}finally{B(false)}}
async function load(){const own=check(await db.from('profiles').select('*').eq('id',uid).maybeSingle());P(own||blank);if(!own){T('Profile');return}PP(check(await db.from('profiles').select('*').neq('id',uid)));L(check(await db.from('likes').select('*')))}
useEffect(()=>{if(!db)return;db.auth.getSession().then(({data,error})=>{S(data.session);if(error)N(error.message)});const {data}=db.auth.onAuthStateChange((event,s)=>{S(s);if(event==='PASSWORD_RECOVERY')R(true)});return()=>data.subscription.unsubscribe()},[]);
useEffect(()=>{PP([]);L([]);C(null);M([]);P(blank);if(uid)run(load)},[uid]);
useEffect(()=>{if(!uid||!selected||tab!=='Chats')return;let active=true,loading=false;async function refresh(){if(loading)return;loading=true;try{const rows=check(await db.from('messages').select('*').or(`and(sender.eq.${uid},recipient.eq.${selected.id}),and(sender.eq.${selected.id},recipient.eq.${uid})`).order('created_at'));if(active)M(rows)}catch(e){if(active)N(e.message)}finally{loading=false}}M([]);refresh();const timer=setInterval(refresh,3000);return()=>{active=false;clearInterval(timer)}},[uid,selected?.id,tab]);
const outgoing=likes.filter(l=>l.sender===uid).map(l=>l.recipient);
const matches=people.filter(p=>outgoing.includes(p.id)&&likes.some(l=>l.sender===p.id&&l.recipient===uid));
if(!db)return <div style={{maxWidth:650,margin:'80px auto',padding:25}}><div className="eyebrow">AFTER HOURS NYC</div><h1>Backend connection required</h1><p>The owner must connect Supabase to enable real accounts, member profiles, and messaging. No fictional profiles are shown.</p><p>Setup instructions: <code>SETUP.md</code></p></div>;
if(!session||recovery)return <div style={{maxWidth:600,margin:'60px auto',padding:25}}><div className="eyebrow">AFTER HOURS NYC · 18+</div><h1>A city of millions.<br/>Find your person.</h1><form className="profile-form" onSubmit={e=>{e.preventDefault();run(async()=>{if(recovery){check(await db.auth.updateUser({password}));R(false);N('Password updated.');return}if(signup){if(!adult)throw Error('Confirm you are 18 or older.');const data=check(await db.auth.signUp({email,password,options:{emailRedirectTo:location.origin}}));if(!data.session)N('Check your email to confirm your account, then sign in.')}else check(await db.auth.signInWithPassword({email,password}));W('')})}}><h2 className="wide">{recovery?'Reset password':signup?'Create account':'Sign in'}</h2>{!recovery&&<label className="wide">Email<input required type="email" autoComplete="email" value={email} onChange={e=>E(e.target.value)}/></label>}<label className="wide">Password<input required type="password" minLength={8} autoComplete={signup||recovery?'new-password':'current-password'} value={password} onChange={e=>W(e.target.value)}/></label>{signup&&!recovery&&<label className="wide"><input style={{display:'inline',width:'auto'}} type="checkbox" required checked={adult} onChange={e=>A(e.target.checked)}/> I confirm I am 18 or older. Self-declaration only.</label>}<button className="primary" disabled={busy}>{busy?'Please wait…':recovery?'Save password':signup?'Create account':'Sign in'}</button></form>{!recovery&&<div className="modal-actions"><button className="secondary" onClick={()=>U(!signup)}>{signup?'Sign in instead':'Create account'}</button><button className="secondary" disabled={busy||!email} onClick={()=>run(async()=>{check(await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin}));N('If this account exists, a reset email will be sent.')})}>Forgot password</button></div>}{notice&&<p role="status">{notice}</p>}</div>;
function card(p){return <article className="card" key={p.id}><div style={{padding:28,background:'#eee0d7'}}><h2>{p.name}, {p.age}</h2><small>{p.borough}</small></div><div className="card-body"><p>{p.bio}</p><div className="modal-actions"><button className="primary" disabled={busy} onClick={()=>run(async()=>{if(outgoing.includes(p.id))check(await db.from('likes').delete().eq('sender',uid).eq('recipient',p.id));else check(await db.from('likes').insert({sender:uid,recipient:p.id}));await load()})}>{outgoing.includes(p.id)?'♥ Liked':'♡ Like'}</button>{matches.some(m=>m.id===p.id)&&<button className="secondary" onClick={()=>{C(p);T('Chats')}}>Chat</button>}</div><div className="moderation"><button disabled={busy} onClick={()=>run(async()=>{check(await db.from('blocks').insert({sender:uid,recipient:p.id}));C(null);await load();N('Profile blocked.')})}>Block</button><button onClick={()=>{Q(p);V('')}}>Report</button></div></div></article>}
return <><aside><a className="brand" href="#" onClick={e=>{e.preventDefault();T('Discover')}}>after hours<span>NYC CONNECTIONS</span></a><div className="nav-label">YOUR NEXT CHAPTER</div><nav>{['Discover','Likes','Chats','Profile'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>T(profile.id?t:'Profile')}><span>{({Discover:'✧',Likes:'♡',Chats:'◌',Profile:'☺'})[t]}</span>{t}</button>)}</nav><div className="side-bottom"><button className="safety" disabled={busy} onClick={()=>run(async()=>check(await db.auth.signOut()))}>Sign out</button></div></aside><main><header>NEW YORK, YOUR WAY · 18+</header>{notice&&<p role="status">{notice}</p>}<section className="page"><h1>{tab==='Discover'?'Find your kind of person.':tab}</h1>
{tab==='Profile'?<form className="profile-form" onSubmit={e=>{e.preventDefault();run(async()=>{check(await db.from('profiles').upsert({id:uid,name:profile.name.trim(),age:Number(profile.age),borough:profile.borough,bio:profile.bio.trim()}));await load();T('Discover');N('Profile saved.')})}}><label>Name<input required maxLength={40} value={profile.name} onChange={e=>P({...profile,name:e.target.value})}/></label><label>Age<input required type="number" min={18} max={100} value={profile.age} onChange={e=>P({...profile,age:e.target.value})}/></label><label>Borough<select value={profile.borough} onChange={e=>P({...profile,borough:e.target.value})}>{boroughs.map(b=><option key={b}>{b}</option>)}</select></label><label className="wide">About you<textarea maxLength={400} rows={4} value={profile.bio} onChange={e=>P({...profile,bio:e.target.value})}/></label><button className="primary" disabled={busy}>Save profile</button></form>:tab==='Chats'?<><button className="secondary" disabled={busy} onClick={()=>run(load)}>Refresh matches</button><div className="chat-layout"><div className="chat-list">{matches.map(p=><button key={p.id} onClick={()=>C(p)}>{p.name}</button>)}{!matches.length&&<p>No mutual matches yet.</p>}</div><div className="conversation">{selected&&matches.some(m=>m.id===selected.id)?<><h3>{selected.name}</h3><div className="bubbles">{messages.map(m=><div className="bubble" style={m.sender!==uid?{alignSelf:'flex-start',background:'#6e606a'}:{}} key={m.id}>{m.body}<small>{new Date(m.created_at).toLocaleString()}</small></div>)}</div><form onSubmit={e=>{e.preventDefault();run(async()=>{if(!body.trim())return;const row=check(await db.from('messages').insert({sender:uid,recipient:selected.id,body:body.trim()}).select().single());M(v=>v.some(m=>m.id===row.id)?v:[...v,row]);D('')})}}><input aria-label="Message" maxLength={1000} value={body} onChange={e=>D(e.target.value)}/><button className="primary" disabled={busy||!body.trim()}>Send</button></form></>:<p>Select a mutual match. Chat requires both people to like each other.</p>}</div></div></>:<><div className="filters"><label><span>BOROUGH</span><select value={borough} onChange={e=>F(e.target.value)}>{['All NYC',...boroughs].map(b=><option key={b}>{b}</option>)}</select></label></div><div className="modal-actions"><button className="secondary" disabled={busy} onClick={()=>run(load)}>Refresh profiles</button></div><div className="grid">{people.filter(p=>(borough==='All NYC'||p.borough===borough)&&(tab!=='Likes'||outgoing.includes(p.id))).map(card)}</div>{!people.length&&<div className="empty"><h2>No other members yet.</h2><p>Profiles appear when real people join. Invite adults you know after publication.</p></div>}</>}
</section><footer>after hours · NYC · Respect boundaries. Meet in public first.</footer></main>{report&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="Report profile"><h2>Report {report.name}</h2><form className="profile-form" onSubmit={e=>{e.preventDefault();run(async()=>{check(await db.from('reports').insert({sender:uid,recipient:report.id,reason:reason.trim()}));Q(null);N('Report saved for the site owner to review.')})}}><label className="wide">Reason<textarea required maxLength={1000} value={reason} onChange={e=>V(e.target.value)}/></label><button className="primary" disabled={busy}>Submit</button><button className="secondary" type="button" onClick={()=>Q(null)}>Cancel</button></form></section></div>}</>;
}
